\c songs_dev;

INSERT INTO songs (name, artist, album, time, is_favorite) VALUES
('I Don''t Care (with Justin Bieber) - Loud Luxury Remix', 'Ed Sheeran', 'I Don''t Care (with Justin Bieber) [Loud Luxury Remix]', '3:14', false),
('Memories - Dillon Francis Remix', 'Maroon 5', 'Memories (Dillon Francis Remix)', '2:42', true),
('All the Time - Don Diablo Remix', 'Zara Larsson', 'All the Time (Don Diablo Remix)', '2:56', false),
('Call You Mine - Keanu Silva Remix', 'The Chainsmokers', 'Call You Mine - The Remixes', '2:49', false),
('Someone You Loved - Future Humans Remix', 'Lewis Capaldi', 'Someone You Loved (Future Humans Remix)', '3:9', true),
('Beautiful People (feat. Khalid) - Jack Wins Remix', 'Ed Sheeran', 'Beautiful People (feat. Khalid) [Jack Wins Remix]', '2:43', false),
('Never Really Over - R3HAB Remix', 'Katy Perry', 'Never Really Over (R3HAB Remix)', '3:7', true),
('Post Malone (feat. RANI) - GATTÜSO Remix', 'Sam Feldt', 'Post Malone (feat. RANI) [GATTÜSO Remix]', '3:27', false),
('Tough Love - Tiësto Remix / Radio Edit', 'Avicii', 'Tough Love (Tiësto Remix)', '3:13', true),
('If I Can''t Have You - Gryffin Remix', 'Shawn Mendes', 'If I Can''t Have You (Gryffin Remix)', '4:13', true),
('Cross Me (feat. Chance the Rapper & PnB Rock) - M-22 Remix', 'Ed Sheeran', 'Cross Me (feat. Chance the Rapper & PnB Rock) [M-22 Remix]', '3:27', false),
('Hate Me - R3HAB Remix', 'Ellie Goulding', 'Hate Me (R3HAB Remix)', '3:23', false),
('Body On My', 'Loud Luxury', 'Body On My', '3:12', true),
('SOS - Laidback Luke Tribute Remix / Radio Edit', 'Avicii', 'SOS (Laidback Luke Tribute Remix)', '2:44', false),
('Summer Days (feat. Macklemore & Patrick Stump of Fall Out Boy) - Tiësto Remix', 'Martin Garrix', 'Summer Days (feat. Macklemore & Patrick Stump of Fall Out Boy) [Remixes]', '4:15', true),
('South of the Border (feat. Camila Cabello & Cardi B) - Andy Jarvis Remix', 'Ed Sheeran', 'South of the Border (feat. Camila Cabello & Cardi B) [Andy Jarvis Remix]', '3:8', false),
('All My Friends - Eden Prince Remix', 'AJ Mitchell', 'All My Friends (Eden Prince Remix)', '2:53', true),
('Say My Name (feat. Bebe Rexha & J Balvin) - Lucas & Steve Remix', 'David Guetta', 'Say My Name (feat. Bebe Rexha & J Balvin) [Lucas & Steve Remix]', '3:9', true),
('Dancing With A Stranger (With Normani) - Cheat Codes Remix', 'Sam Smith', 'Dancing With A Stranger (With Normani) [Cheat Codes Remix]', '2:39', true),
('Let It Be Me - Sondr Remix', 'Steve Aoki', 'Let It Be Me (Remixes)', '3:5', false),
('Heaven - David Guetta & MORTEN Remix', 'Avicii', 'Heaven (David Guetta & MORTEN Remix)', '3:35', true),
('All Around The World (La La La) - Marnik Remix', 'R3HAB', 'All Around The World (La La La) [Marnik Remix]', '2:50', true),
('Don''t Leave Me Alone (feat. Anne-Marie) - EDX''s Indian Summer Remix', 'David Guetta', 'Don''t Leave Me Alone (feat. Anne-Marie) [EDX''s Indian Summer Remix]', '3:30', true),
('Slow Dance (feat. Ava Max) - Sam Feldt Remix', 'AJ Mitchell', 'Slow Dance (feat. Ava Max) [Sam Feldt Remix]', '3:13', true),
('Do You Mean (feat. Ty Dolla $ign & bülow) - Myon Remix', 'The Chainsmokers', 'Do You Mean - The Remixes (feat. Ty Dolla $ign & bülow)', '3:25', true),
('Hold Me While You Wait - Steve Void Remix', 'Lewis Capaldi', 'Hold Me While You Wait (Steve Void Remix)', '2:52', true),
('One Thing Right - Firebeatz Remix', 'Marshmello', 'One Thing Right (Remixes)', '3:12', true),
('Close To Me (with Diplo) (feat. Swae Lee) - CID Remix', 'Ellie Goulding', 'Close To Me (Remixes)', '2:55', true),
('So Am I - Toby Green Remix', 'Ava Max', 'So Am I (Toby Green Remix)', '2:46', false),
('When You Leave - Breathe Carolina Remix', 'Nikki Vianna', 'When You Leave (Breathe Carolina Remix)', '2:35', true),
('Mother - Fedde Le Grand Remix', 'Charlie Puth', 'Mother (Fedde Le Grand Remix)', '2:58', false),
('Signs - Eden Prince Remix', 'Starley', 'Signs (Eden Prince Remix)', '2:52', true),
('Ruin My Life - Steve James Remix', 'Zara Larsson', 'Ruin My Life (Remixes)', '2:57', true),
('Torn - KREAM Remix', 'Ava Max', 'Torn (KREAM Remix)', '2:49', true),
('Quite Miss Home - Steve Void Remix', 'James Arthur', 'Quite Miss Home (Steve Void Remix)', '3:40', true),
('Love Me Less (feat. Quinn XCII) - Party Pupils Remix', 'MAX', 'Love Me Less (Remixes)', '3:5', true),
('Happier - Matt Medved Remix', 'Marshmello', 'Happier (Remixes Pt. 2)', '2:50', true),
('Side Effects - Fedde Le Grand Remix', 'The Chainsmokers', 'Side Effects - Remixes', '2:52', false),
('Good Things Fall Apart (with Jon Bellion) [Tiësto''s Big Room Remix]', 'ILLENIUM', 'Good Things Fall Apart (with Jon Bellion) [Tiësto''s Big Room Remix]', '4:7', false),
('Paradise - Bazzi vs. Black Caviar Remix', 'Bazzi vs.', 'Paradise (Bazzi vs. Black Caviar Remix)', '3:38', true),
('White Mercedes - EDX''s Miami Sunset Remix', 'Charli XCX', 'White Mercedes (EDX''s Miami Sunset Remix)', '3:20', true),
('Higher Love', 'Kygo', 'Higher Love', '3:48', true),
('Unlove You', 'Armin van Buuren', 'Unlove You', '2:30', true),
('bad guy (with Justin Bieber)', 'Billie Eilish', 'bad guy (with Justin Bieber)', '3:14', true),
('Freaking Me Out - Keanu Silva Remix', 'Ava Max', 'Freaking Me Out (Keanu Silva Remix)', '2:57', true),
('Heaven Can Wait - The Aston Shuffle Remix', 'Sia', 'Heaven Can Wait (The Aston Shuffle Remix)', '3:38', false),
('When It Comes To You - Benny Benassi & BB Team Remix', 'Sean Paul', 'When It Comes To You (Remixes)', '2:24', true),
('Gone - The Wild Remix', 'Charli XCX', 'Gone (The Wild Remix)', '3:13', false),
('American Boy - Brooks Remix', 'Estelle', 'American Boy (Brooks Remix)', '3:20', false),
('Million Pieces - M-22 Remix', 'Bastille', 'Million Pieces (M-22 Remix)', '2:46', true),
('joy. (R3HAB Remix)', 'for KING & COUNTRY', 'joy. (R3HAB Remix)', '2:51', false),
('Crash Into Me - Settle Down Steavis Aoki Remix', 'Steve Aoki', 'Crash Into Me (Settle Down Steavis Aoki Remix)', '4:26', false),
('Old Town Road - Diplo Remix', 'Lil Nas X', 'Old Town Road (Diplo Remix)', '3:24', false),
('Lovers + Strangers - GATTÜSO Remix', 'Starley', 'Lovers + Strangers (GATTÜSO Remix)', '3:23', false),
('Promises (with Sam Smith) - David Guetta Remix', 'Calvin Harris', 'Promises (with Sam Smith) [Remixes]', '3:10', true),
('Flames (with ZAYN) - R3HAB & Skytech VIP Remix', 'R3HAB', 'Flames (with ZAYN) (R3HAB & Skytech VIP Remix)', '3:57', true),
('What Am I - SONDR Remix', 'Why Don''t We', 'What Am I (SONDR Remix)', '3:0', false),
('Cool Kids', 'Olympis', 'Cool Kids', '2:19', false),
('Loco Contigo (with J. Balvin & Tyga) - Cedric Gervais Remix', 'DJ Snake', 'Loco Contigo (with J. Balvin & Tyga) [Cedric Gervais Remix]', '4:39', true),
('All Star - Breathe Carolina Remix', 'Smash Mouth', 'All Star (Breathe Carolina Remix)', '3:37', false),
('Trampoline - Dave Audé Remix', 'SHAED', 'Melt (Deluxe)', '3:50', true),
('Stay (Don''t Go Away) [feat. Raye] - Mark Knight Remix', 'David Guetta', 'Stay (Don''t Go Away) [feat. Raye] [Mark Knight Remix]', '3:8', true),
('With You - Dexter Remix', 'Kaskade', 'With You - The Remixes', '3:16', false),
('Safety (feat. DJ Snake) - Dark Heart 2am Mix', 'GASHI', 'Safety (The Dark Heart Remixes) (feat. DJ Snake)', '3:30', true),
('Beautiful (feat. Camila Cabello) - Bazzi vs. EDX''s Ibiza Sunrise Remix', 'Bazzi vs.', 'Beautiful (feat. Camila Cabello) [Bazzi vs. EDX''s Ibiza Sunrise Remix]', '3:7', true),
('Talk - Disclosure VIP', 'Khalid', 'Talk (Disclosure VIP)', '4:33', false),
('Spicy - Majestic Remix', 'Herve Pagez', 'Spicy (with Diplo & Charli XCX) [Remixes]', '4:15', false),
('Don''t Leave Me Lonely (feat. Yebba) - Claptone Remix', 'Mark Ronson', 'Don''t Leave Me Lonely (feat. Yebba) [Claptone Remix]', '3:36', false),
('Treehouse - R3HAB Remix', 'James Arthur', 'Treehouse (R3HAB Remix)', '3:12', true),
('Hearts Ain''t Gonna Lie - Eden Prince Remix', 'Arlissa', 'Hearts Ain''t Gonna Lie (Remixes, Pt. 1)', '3:58', true),
('Call You Mine', 'The Chainsmokers', 'World War Joy', '3:37', false),
('Post Malone (feat. RANI)', 'Sam Feldt', 'Magnets EP', '2:54', false),
('Here With Me', 'Marshmello', 'Here With Me', '2:36', false),
('Easier - Seeb Remix', '5 Seconds of Summer', 'Easier (Seeb Remix)', '2:45', false),
('Sixteen', 'Ellie Goulding', 'Sixteen', '3:21', false),
('Never Really Over', 'Katy Perry', 'Never Really Over', '3:43', true),
('All You Need To Know (feat. Calle Lehmann)', 'Gryffin', 'All You Need To Know (feat. Calle Lehmann)', '3:58', false),
('I Miss Myself (with HRVY)', 'NOTD', 'I Miss Myself (with HRVY)', '3:11', false),
('South of the Border (feat. Camila Cabello & Cardi B) - Sam Feldt Remix', 'Ed Sheeran', 'South of the Border (feat. Camila Cabello & Cardi B) [Sam Feldt Remix]', '2:53', true),
('Takeaway (feat. Lennon Stella)', 'The Chainsmokers', 'World War Joy...Takeaway', '3:29', true),
('All the Time', 'Zara Larsson', 'All the Time', '3:48', false),
('What I Like About You (feat. Theresa Rex)', 'Jonas Blue', 'What I Like About You (feat. Theresa Rex)', '3:40', true),
('With You', 'Kaskade', 'With You', '3:0', false),
('Body Back (feat. Maia Wright)', 'Gryffin', 'Body Back (feat. Maia Wright)', '3:34', true),
('Not Ok', 'Kygo', 'Not Ok', '3:30', false),
('Ruin My Life', 'Zara Larsson', 'Ruin My Life', '3:10', true),
('I Wanna Know (feat. Bea Miller)', 'NOTD', 'I Wanna Know (feat. Bea Miller)', '3:17', false),
('Better With You', '3LAU', 'Better With You', '3:12', true),
('Carry On (from the Original Motion Picture "POKÉMON Detective Pikachu")', 'Kygo', 'Carry On (from the Original Motion Picture "POKÉMON Detective Pikachu")', '3:35', false),
('Polaroid', 'Jonas Blue', 'Blue', '3:13', false),
('Lost In Japan - Remix', 'Shawn Mendes', 'Lost In Japan (Remix)', '3:21', false),
('In Your Arms (with X Ambassadors)', 'ILLENIUM', 'ASCEND', '3:40', true),
('I''m Not Alright', 'Loud Luxury', 'I''m Not Alright', '3:5', false),
('SOS', 'Avicii', 'SOS', '2:37', false),
('Harder', 'Jax Jones', 'Snacks', '2:39', false),
('The Middle', 'Zedd', 'The Middle', '3:4', false),
('Wanted', 'NOTD', 'Wanted', '2:40', false);